blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("userauth.urls")),
    path('pingtai/',include("pingtai.urls")),
    path('self/',include("self.urls")),
    path('ckeditor/',include("ckeditor_uploader.urls")),
    path('captcha/', include('captcha.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pingtai/urls.py
from django.urls import path,include
from . import views
app_name="pingtai"
urlpatterns = [
    path('', views.index,name="index"),
    path('getKeyword/', views.getKeyword,name="getKeyword"),
    path('<int:con_id>/detail/', views.detail,name="detail"),
    path('kaitong/', views.kaitong,name="kaitong"),
    path('links/', views.links, name='links'),

]

pingtai/models.py
from django.db import models
from django.utils.html import format_html
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
# Create your models here.


class Category(models.Model):
    name=models.CharField(verbose_name='分类',max_length=20)
    def listKeyword(self):
        objs=self.keyword_set.all()
        arr=[]
        for item in objs:
            arr.append("<e style='margin:0 5px'>"+item.name+"</e>")
        return format_html("".join(arr))
    listKeyword.short_description='关键字'
    def __str__(self):
        return self.name
    class Meta:
        verbose_name="分类管理"
        verbose_name_plural = "分类管理"

    @classmethod
    def getAll(cls):
        return cls.objects.all()


class keyword(models.Model):
    name = models.CharField(verbose_name='关键字',max_length=20)
    c=models.ForeignKey(to=Category,on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class PTArticle(models.Model):
    c=models.ForeignKey(verbose_name='分类',to=Category,on_delete=models.CASCADE)
    k=models.ForeignKey(verbose_name='关键字',to=keyword,on_delete=models.CASCADE)
    a=models.ForeignKey(verbose_name='作者',to=User,on_delete=models.CASCADE)
    title=models.CharField(verbose_name='文章标题',max_length=50)
    con=RichTextField(verbose_name='文章内容',max_length=20000)
    c_time=models.DateTimeField(auto_now_add=True)
    u_time=models.DateTimeField(auto_now=True)
    status=models.BooleanField(default=False,verbose_name='发布状态')
    class Meta:
        verbose_name="文章管理"
        verbose_name_plural = "文章管理"

    @classmethod
    def getAll(cls):
        return cls.objects.filter(status=True)
from userauth.models import User
class UserInfo(models.Model):
    u=models.OneToOneField(to=User,on_delete=models.CASCADE,verbose_name="用户")
    company=models.CharField(max_length=20,verbose_name="公司")
    position=models.CharField(max_length=20,verbose_name="职位")
    honny=models.CharField(max_length=20,verbose_name="爱好")
    reason=models.TextField(max_length=200,verbose_name="申请理由")
    realname = models.CharField(max_length=10, verbose_name="真实姓名")
    sh=models.IntegerField(default=1,choices=(
        (0,"未审核"),
        (1,"审核中"),
        (2,"审核通过"),
    ))
    class Meta:
        verbose_name="开通管理"
        verbose_name_plural = "开通管理"

    @classmethod
    def getAll(cls):
        return cls.objects.all()
class Ping(models.Model):
    c = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='评论用户')
    e = models.ForeignKey(to=PTArticle, on_delete=models.CASCADE, verbose_name='文章')
    nei = models.CharField(max_length=2000, verbose_name='评论内容')
    ctime = models.DateTimeField(auto_now_add=True)

    @classmethod
    def getAll(cls):
        return cls.objects.all()

pingtai/forms.py
from django import forms
from .models import UserInfo

class UserInfoForm(forms.ModelForm):
    class Meta:
        fields="__all__"
        model=UserInfo

        widgets = {
            'company': forms.TextInput(attrs={
                'class': 'admin_input_style'
            }),
            'position': forms.TextInput(attrs={
                'class': 'admin_input_style'
            }),
            'honny': forms.TextInput(attrs={
                'class': 'admin_input_style'
            }),
            'reason': forms.Textarea(attrs={
                'class': 'admin_input_style'
            }),
            'realname': forms.TextInput(attrs={
                'class': 'admin_input_style'
            }),
        }

pingtai/views.py
from django.shortcuts import render,reverse,redirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import keyword,Category,PTArticle,UserInfo,Ping
from userauth.models import User
from django.http import HttpResponse
from .forms import UserInfoForm
from .fangjia1 import reg
import pandas as pd
import os
# Create your views here.
def index(request):
    if request.method=='GET':
        data=Category.getAll()
        article=PTArticle.objects.all()
        username=request.session.get("username")
        userInfo=UserInfo.objects.all()
        return render(request,"pingtai/index.html",{'data':data,'article':article,'username':username,'userinfo':userInfo})

@csrf_exempt
def getKeyword(request):
    if request.is_ajax():
        c=request.POST.get('c',None)
        res=keyword.objects.filter(c=c).values_list('id','name')
        obj={}
        for arr in res:
            obj[arr[0]]=arr[1]
        return JsonResponse(obj)

def detail(request,con_id):
    con=PTArticle.objects.filter(id=con_id).first()
    return render(request,'pingtai/xiangqing.html',{"con":con})

def kaitong(request):
    if request.method == "GET":
        username = request.session.get("username",None)
        if username:
            obj=User.objects.filter(username=username).first()
            c=obj.c
            if int(c)==0:
                form=UserInfoForm({'u':obj.id,'sh':1})
                return render(request,'pingtai/kaitong.html',{'form':form})
            else:
              return HttpResponse('用户后台')
        else:
            return redirect(reverse("userauth:login"))
    else:
        form=UserInfoForm(request.POST)
        if form.is_valid():
            form.save()
            #username = request.session.get("username", None)
            #User.objects.filter(username=username).update()
            return redirect(reverse("pingtai:index"))
        else:
            return render(request, 'pingtai/kaitong.html', {'form': form})

from sklearn.linear_model import LinearRegression
def links(request):
  if request.method == 'GET':
    return render(request, 'pingtai/links.html')
  else:
    dist = request.POST.get("dist")
    if dist == 'dist_dongcheng':
      dist = '10000'
    elif dist == 'dist_fengtai':
      dist = '01000'
    elif dist == 'dist_haidian':
      dist = '00100'
    elif dist == 'dist_shijingshan':
      dist = '00010'
    elif dist == 'dist_xicheng':
      dist = '00001'
    elif dist == 'dist_chaoyang':
      dist = '00000'
    data = []
    roomnum = request.POST.get("roomnum")
    halls = request.POST.get("halls")
    area = request.POST.get("area")
    floor = request.POST.get("floor")
    if floor == 'floor_low':
      floor = '10'
    elif floor == 'floor_middle':
      floor = '01'
    elif floor == 'floor_high':
      floor = '00'
    subway = request.POST.get("subway")
    school = request.POST.get("school")
    for i in dist:
      data.append(int(i))
    data.append(int(roomnum))
    data.append(int(halls))
    data.append(float(area))
    for i in floor:
      data.append(int(i))
    data.append(int(subway))
    data.append(int(school))
    df = pd.read_csv(os.path.join("uploads",'house_price.csv'))
    df1=pd.get_dummies(df[['dist','floor']])
    del df1["dist_chaoyang"]
    del df1["floor_high"]
    df2 = pd.concat([df1, df], axis=1)
    del df2["dist"]
    del df2["floor"]
    X = df2.iloc[:, :-1]
    # print(X.head())
    y = df2["price"]
    from sklearn.linear_model import LinearRegression  # 普通最小二乘线性回归
    reg = LinearRegression(normalize=True)  # 岭回归
    reg = reg.fit(X, y)
    result=int(reg.predict([data])[0])
    print(reg.score(X,y))
    return render(request, 'pingtai/links.html',{'dist':dist,'roomnum':roomnum,'halls':halls,'floor':floor,'area':area,'subway':subway,'school':school,'price':result})

pingtai/templates/pingtai/kaitong.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>申请开通博客</title>
</head>
<body>
  <div class="top">
    <div class="yuan"></div>
    <span>申请开通博客</span>
  </div>
  <div class="content">
    <div class="one">
      <span>本博客网站是面向程序员的高质量IT技术学习与分享平台，博客是学习与分享知识的工具。</span>
    </div>
    <div class="two">
      <span>博客申请由人工审核，请认真前些您的申请理由，说明您在博客主要分享哪方面的内容。</span>
    </div>

    <form action="/pingtai/kaitong/" method="post">
      {% csrf_token %}
      {{form.u}}
      {{form.sh}}
      <span>真实姓名：</span>
      {{form.realname}}<br>
      <!--<input type="text"><br>-->
      <span>公&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp司：</span>
      {{form.company}}<br>
      <!--<input type="text"><br>-->
      <span>职&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp位：</span>
      {{form.position}}<br>
      <!--<input type="text"><br>-->
      <div class="box">技术兴趣：</div>
      {{form.honny}}<br>
      <!--<div class="te"><textarea name="" id="" cols="90" rows="5"></textarea></div>-->
       <div class="liyou">
        <span>申请理由:</span><br>
        {{form.reason}}
        <!--<textarea name="" id="" cols="100" rows="9"></textarea>-->
      </div>
      <button >提交</button>
    </form>
  </div>
</body>
</html>

<style>
  .top{
    width: 60%;
    height: 30px;
    margin-left: 100px;
    border-bottom: 2px solid #BDCFDC;
    line-height: 40px;
    overflow: hidden;
  }
  .top .yuan{
    width: 10px;
    height: 10px;
    border-radius: 50%;
    background-color: #2c81ba;
    margin-top: 15px;
    margin-right: 5px;
    float: left;
  }
  .content{
     width: 70%;
    height: 30px;
    margin-left: 100px;
    margin-top: 10px;
  }
  .content .one{
    font-weight: 600;
    margin-bottom: 3px;
  }
   .content .two{
    margin-bottom: 10px;
  }
   .content .liyou{
    margin-bottom: 20px;
  }
   .content input{
    margin-left: 5px;
     margin-bottom: 5px;
  }
  .content .box{
    float: left;
  }
  .te textarea{
    margin-left: 8px;
    margin-bottom: 10px;
  }
  .content button{
    width: 100px;
    margin-left: 300px;
  }
</style>

pingtai/templates/pingtai/links.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  {% load static %}
  <script src="{% static 'pingtai/js/jquery.min.js' %}"></script>
</head>
<body>
<div class="fy">
  <h2>录入房源</h2>
</div>
<form action="{% url 'pingtai:links' %}" method="post">
  {% csrf_token %}
  <div class="dist">
    区域:
    <select name="dist">
      <option value="dist_chaoyang">朝阳</option>
      <option value="dist_dongcheng">城东</option>
      <option value="dist_fengtai">丰台</option>
      <option value="dist_haidian">海淀</option>
      <option value="dist_shijingshan">石景山</option>
      <option value="dist_xicheng">西城</option>
    </select>
  </div>
     <div class="roomnum">
      几室:
       <select name="roomnum" id="roomnum">
        <option value="1" >一室</option>
        <option value="2" >二室</option>
        <option value="3" >三室</option>
        <option value="4" >四室</option>
        <option value="5" >五室</option>
      </select>
    </div>
      <div class="halls">
    几厅:
      <select name="halls" id="halls">
        <option value="0" >0厅</option>
        <option value="1" >1厅</option>
        <option value="2" >2厅</option>
        <option value="3" >3厅</option>
      </select>
    </div>
   <div class="area">
    面积:
    <input type="text" name="area" >
  </div>
  <div class="floor">
    楼层:
    <select name="floor" >
      <option value="floor_low" >低楼层</option>
      <option value="floor_middle" >中楼层</option>
      <option value="floor_high" >高楼层</option>
    </select>
  </div>
  <div class="subway" >
    是否靠近地铁:
        <input type="radio" name="subway" value="1">是
        <input type="radio" name="subway" value="0">否
  </div>
   <div class="school">
    是否靠近学校:
        <input type="radio" name="school" value="1">是
        <input type="radio" name="school" value="0">否
  </div>
  <button type="submit">提交</button>
  <div class="price">
    预测售价:￥{{price}}元/㎡
 </div>
</form>

</body>
</html>
<script>

</script>