blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("userauth.urls")),
    path('pingtai/',include("pingtai.urls")),
    path('self/',include("self.urls")),
    path('ckeditor/',include("ckeditor_uploader.urls")),
    path('captcha/', include('captcha.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pingtai/urls.py
from django.urls import path,include
from . import views
app_name="pingtai"
urlpatterns = [
    path('', views.index,name="index"),
    path('getKeyword/', views.getKeyword,name="getKeyword"),
    path('<int:con_id>/detail/', views.detail,name="detail"),
    path('kaitong/', views.kaitong,name="kaitong"),
    path('links/', views.links, name='links'),

]

self/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from . import views
app_name='self'
urlpatterns = [
    path('', views.index,name='index'),
    path('selfinfo/', views.selfinfo,name='selfinfo'),
    path('liuyan/', views.liuyan,name='liuyan'),
    path('lianjie/', views.lianjie,name='lianjie'),
    path('loginout/', views.loginout,name='loginout'),
    path('guanli/', views.guanli,name='guanli'),
    path('upload/', views.upload,name='upload'),
    path('img/', views.img,name='img'),
    path('passed/', views.passed,name='passed'),
    path('article/', views.article,name='article'),#管理文章
    path('addArticle/', views.addArticle,name='addArticle'),#添加文章
]

self/models.py
from django.db import models
from userauth.models import User
from pingtai.models import PTArticle,Category,keyword
from ckeditor.fields import RichTextField

class Article(models.Model):
  c = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name='分类')
  k = models.ForeignKey(to=keyword, on_delete=models.CASCADE, verbose_name='关键字')
  a = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='作者')
  title = models.CharField(max_length=50, verbose_name='文章标题')
  con = RichTextField(max_length=30000, verbose_name='文章内容')
  c_time = models.DateTimeField(auto_now_add=True)
  u_time = models.DateTimeField(auto_now=True)
  status = models.BooleanField(default=False, verbose_name='发布状态')
  look = models.IntegerField(default=0)

self/forms.py
from django import forms
from pingtai.models import User
from .models import Article

class SelfInfoForm(forms.ModelForm):
  class Meta:
    model=User
    fields="__all__"
    exclude=['c','img']
    widgets = {
      'username': forms.TextInput(attrs={
        'class': 'input w50'
      }),
      'password': forms.TextInput(attrs={
        'class': 'input w50'
      }),
      'email': forms.EmailInput(attrs={
        'class': 'input w50'
      }),
      'tel': forms.TextInput(attrs={
        'class': 'input w50'
      })
    }

class ArticleForm(forms.ModelForm):
  class Meta:
    fields=['title','c','k','con','status']
    model=Article

self/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse,JsonResponse
import os.path
from userauth.models import User as Us
from pingtai.models import Category,keyword
from django.conf import settings   #在blog里的都是配置项conf,因此需要这样引
# from django.views.decorators

# Create your views here.
from util.myutil import authuser
from .forms import ArticleForm,User

@authuser
def index(request):
  if request.method == 'GET':
    name = request.session.get('name', None)
    return render(request, 'self/index.html', {'name': name})

@authuser
def lianjie(request):
  if request.method == 'GET':
    name = request.session.get('name', None)
    return render(request, 'self/lianjie.html', { 'name': name})

@authuser
def selfadmin(request):
  if request.method == 'GET':
    name = request.session.get('name', None)
    return render(request, 'self/index.html', { 'name': name})
@authuser
def selfinfo(request):
  if request.method == 'GET':
    name = request.session.get('name', None)
    return render(request, 'self/selfinfo.html', { 'name': name})

@authuser
def liuyan(request):
  if request.method == 'GET':
    name = request.session.get('name', None)
    return render(request, 'self/liuyan.html', { 'name': name})

@authuser
def guanli(request):
  if request.method == 'GET':
    name = request.session.get('name', None)
    return render(request, 'self/guanli.html', { 'name': name})

@authuser
def passed(request):
  if request.method == 'GET':
    name = request.session.get('name', None)
    return render(request, 'self/passed.html', {'name': name})

# @authuser
# def upload(request):
#   if request.method == 'POST':
#     img=request.FILES['img']
#     name=img.name
#     with open('uploads/%s'%name,'wb+') as destination:
#       for chunk in img.chunks():
#         destination.write(chunk)
#     return HttpResponse("ok")

@authuser
def upload(request):
  if request.method == 'GET':
    name = request.session.get('name', None)
    return render(request, 'self/upload.html', {'name': name})

@authuser
def img(request):
    name = request.session.get('username', None)
    names=name
    if request.is_ajax():
      img = request.FILES.get('upload',None)
      name=os.path.join("uploads","userimg",img.name)
      if img:
        with open(name,"wb+") as f:   #拼接成一个路径
          for chunk in img.chunks():
            f.write(chunk)
            Us.objects.filter(username=names).update(img=os.path.join("userimg",img.name))
      return JsonResponse({"status":"ok","src":os.path.join(settings.MEDIA_URL,'userimg',img.name)})


def article(request):
  username = request.session.get('username', None)
  if request.method == 'GET':
    uobj=Us.objects.filter(username=username).first()
    articles=uobj.article_set.all()
    c=Category.objects.all()
    k=keyword.objects.all()
    return render(request, 'self/article.html',{'articles':articles,'c':c,'k':k})

@authuser
def addArticle(request):
  username = request.session.get('username', None)
  cate = Category.objects.all()
  if request.method == 'GET':
    form = ArticleForm()
    return render(request, 'self/addArticle.html',{'form':form,'cate':cate})
  else:
    form=ArticleForm(request.POST)
    if form.is_valid():
      obj=form.save(commit=False)
      obj.a_id = User.objects.filter(username=username).first().id
      obj.save()
      return redirect(reverse('self:addArticle'))
    return render(request, 'self/addArticle.html', {'form': form,'cate':cate})


def loginout(request):
  del request.session['username']
  return redirect(reverse('pingtai:index'))

self/templates/self/index.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>个人主页</title>
  {% load static %}
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp"/>
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="Amaze UI"/>
  <link rel="stylesheet" href="{% static 'self/assets/css/amazeui.min.css' %}">
  <link rel="stylesheet" href="{% static 'self/assets/css/app.css' %}">
</head>

<body id="blog">

<!-- nav start -->
<nav class="am-g am-g-fixed blog-fixed blog-nav">
<button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only blog-button" data-am-collapse="{target: '#blog-collapse'}" ></button>

  <div class="am-collapse am-topbar-collapse" id="blog-collapse">
    <ul class="am-nav am-nav-pills am-topbar-nav">
      <li class="am-active"><a href="{% url 'self:index'%}">首页</a></li>
      <li><a href="{% url 'pingtai:index'%}">回到博客</a></li>
      <!--<li><a href="lw-article-fullwidth.html">更新</a></li>-->
      <li><a href="{% url 'self:liuyan'%}">留言</a></li>
      <li><a href="{% url 'self:lianjie'%}">链接</a></li>
      <li><a href="{% url 'self:loginout'%}">退出</a></li>
      <li><a href="{% url 'self:guanli'%}">管理</a></li>
    </ul>
    <form class="am-topbar-form am-topbar-right am-form-inline" role="search">
      <div class="am-form-group">
        <input type="text" class="am-form-field am-input-sm" placeholder="搜索">
      </div>
    </form>
  </div>
</nav>
<hr>
<!-- nav end -->
<!-- banner start -->
<div class="am-g am-g-fixed blog-fixed am-u-sm-centered blog-article-margin">
    <div data-am-widget="slider" class="am-slider am-slider-b1" data-am-slider='{&quot;controlNav&quot;:false}' >
    <ul class="am-slides">
      <li>
            <img src="{% static 'self/assets/i/b1.jpg' %}">
            <div class="blog-slider-desc am-slider-desc ">
                <div class="blog-text-center blog-slider-con">
                    <span><a href="" class="blog-color">Article &nbsp;</a></span>
                    <h1 class="blog-h-margin"><a href="">总在思考一句积极的话</a></h1>
                    <p>那时候刚好下着雨，柏油路面湿冷冷的，还闪烁着青、黄、红颜色的灯火。
                    </p>
                    <span class="blog-bor">2015/10/9</span>
                    <br><br><br><br><br><br><br>
                </div>
            </div>
      </li>
      <li>
            <img src="{% static 'self/assets/i/b2.jpg' %}">
            <div class="am-slider-desc blog-slider-desc">
                <div class="blog-text-center blog-slider-con">
                    <span><a href="" class="blog-color">Article &nbsp;</a></span>
                    <h1 class="blog-h-margin"><a href="">总在思考一句积极的话</a></h1>
                    <p>那时候刚好下着雨，柏油路面湿冷冷的，还闪烁着青、黄、红颜色的灯火。
                    </p>
                    <span>2015/10/9</span>
                </div>
            </div>
      </li>
      <li>
            <img src="{% static 'self/assets/i/b3.jpg' %}">
            <div class="am-slider-desc blog-slider-desc">
                <div class="blog-text-center blog-slider-con">
                    <span><a href="" class="blog-color">Article &nbsp;</a></span>
                    <h1 class="blog-h-margin"><a href="">总在思考一句积极的话</a></h1>
                    <p>那时候刚好下着雨，柏油路面湿冷冷的，还闪烁着青、黄、红颜色的灯火。
                    </p>
                    <span>2015/10/9</span>
                </div>
            </div>
      </li>
      <li>
            <img src="{% static 'self/assets/i/b2.jpg' %}">
            <div class="am-slider-desc blog-slider-desc">
                <div class="blog-text-center blog-slider-con">
                    <span><a href="" class="blog-color">Article &nbsp;</a></span>
                    <h1 class="blog-h-margin"><a href="">总在思考一句积极的话</a></h1>
                    <p>那时候刚好下着雨，柏油路面湿冷冷的，还闪烁着青、黄、红颜色的灯火。
                    </p>
                    <span>2015/10/9</span>
                </div>
            </div>
      </li>
    </ul>
    </div>
</div>
<!-- banner end -->

<!-- content srart -->
<div class="am-g am-g-fixed blog-fixed">
    <div class="am-u-md-8 am-u-sm-12">

        <article class="am-g blog-entry-article">
            <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-img">
                <img src="{% static 'self/assets/i/f10.jpg' %}" alt="" class="am-u-sm-12">
            </div>
            <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-text">
                <span><a href="" class="blog-color">article &nbsp;</a></span>
                <span> @amazeUI &nbsp;</span>
                <span>2015/10/9</span>
                <h1><a href="{% url 'self:selfinfo'%}">我本楚狂人，凤歌笑孔丘</a></h1>
                <p>我们一直在坚持着，不是为了改变这个世界，而是希望不被这个世界所改变。
                </p>
                <p><a href="" class="blog-continue">continue reading</a></p>
            </div>
        </article>

        <article class="am-g blog-entry-article">
            <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-img">
                <img src="{% static 'self/assets/i/f6.jpg' %}" alt="" class="am-u-sm-12">
            </div>
            <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-text">
                <span><a href="" class="blog-color">article&nbsp;</a></span>
                <span>@amazeUI &nbsp;</span>
                <span>2015/10/9</span>
                <h1><a href="{% url 'self:selfinfo'%}">世间所有的相遇，都是久别重逢。</a></h1>
                <p>你可以选择在原处不停地跟周遭不解的人解释你为何这么做，让他们理解你，你可以选择什么都不讲，自顾自往前走。
                </p>
                <p><a href="" class="blog-continue">continue</a></p>
            </div>
        </article>

        <article class="am-g blog-entry-article">
            <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-img">
                <img src="{% static 'self/assets/i/f12.jpg' %}" alt="" class="am-u-sm-12">
            </div>
            <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-text">
                <span><a href="" class="blog-color">article&nbsp;</a></span>
                <span>@amazeUI</span>
                <span>2015/10/9</span>
                <h1><a href="{% url 'self:selfinfo'%}">陌上花开，可缓缓归矣。</a></h1>
                <p>那时候刚好下着雨，柏油路面湿冷冷的，还闪烁着青、黄、红颜色的灯火。我们就在骑楼下躲雨，看绿色的邮筒孤独地站在街的对面。
                </p>
                <p><a href="" class="blog-continue">continue</a></p>
            </div>
        </article>

        <article class="am-g blog-entry-article">
            <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-img">
                <img src="{% static 'self/assets/i/f22.jpg' %}" alt="" class="am-u-sm-12">
            </div>
            <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-text">
                <span><a href="" class="blog-color">article&nbsp;</a></span>
                <span>@amazeUI</span>
                <span>2015/10/9</span>
                <h1><a href="{% url 'self:selfinfo'%}">爱自己是终生浪漫的开始</a></h1>
                <p>the whole of life becomes an act of letting go, but what always hurts the most is not taking a moment to say goodbye
                </p>
                <p><a href="" class="blog-continue">continue</a></p>
            </div>
        </article>

        <article class="am-g blog-entry-article">
            <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-img">
                <img src="{% static 'self/assets/i/f18.jpg' %}" alt="" class="am-u-sm-12">
            </div>
            <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-text">
                <span><a href="" class="blog-color">article&nbsp;</a></span>
                <span> @amazeUI &nbsp;</span>
                <span>2015/10/9</span>
                <h1><a href="{% url 'self:selfinfo'%}">My dear amazeUI, Hello </a></h1>
                <p>那时候刚好下着雨，柏油路面湿冷冷的，还闪烁着青、黄、红颜色的灯火。我们就在骑楼下躲雨，看绿色的邮筒孤独地站在街的对面。
                </p>
                <p><a href="" class="blog-continue">continue reading</a></p>
            </div>
        </article>

        <article class="am-g blog-entry-article">
            <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-img">
                <img src="{% static 'self/assets/i/f20.jpg' %}" alt="" class="am-u-sm-12">
            </div>
            <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-text">
                <span><a href="" class="blog-color">article&nbsp;</a></span>
                <span> @amazeUI &nbsp;</span>
                <span>2015/10/9</span>
                <h1><a href="{% url 'self:selfinfo'%}">My way or the highway</a></h1>
                <p>A big wind rises， clouds are driven away. Home am Inow the world is under my sway. Where are brave men to guard the four frontiers today！
                </p>
                <p><a href="" class="blog-continue">continue reading</a></p>
            </div>
        </article>

         <article class="am-g blog-entry-article">
            <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-img">
                <img src="{% static 'self/assets/i/f19.jpg' %}" alt="" class="am-u-sm-12">
            </div>
            <div class="am-u-lg-6 am-u-md-12 am-u-sm-12 blog-entry-text">
                <span><a href="" class="blog-color">article&nbsp;</a></span>
                <span> @amazeUI &nbsp;</span>
                <span>2015/10/9</span>
                <h1><a href="{% url 'self:selfinfo'%}">一想到你，我这张丑脸上就泛起微笑</a></h1>
                <p>那一天我二十一岁，在我一生的黄金时代。我有好多奢望。我想爱，想吃，还想在一瞬间变成天上半明半暗的云。
                </p>
                <p><a href="" class="blog-continue">continue reading</a></p>
            </div>
        </article>

        <ul class="am-pagination">
  <li class="am-pagination-prev"><a href="">&laquo; Prev</a></li>
  <li class="am-pagination-next"><a href="">Next &raquo;</a></li>
</ul>
    </div>

    <div class="am-u-md-4 am-u-sm-12 blog-sidebar">
        <div class="blog-sidebar-widget blog-bor">
            <h2 class="blog-text-center blog-title"><span>About</span></h2>
            <img src="{% static 'self/assets/i/f14.jpg' %}" alt="about me" class="blog-entry-img" >
            <p>妹纸UI</p>
            <p>{{name}}</p>
        </div>
        <div class="blog-sidebar-widget blog-bor">
            <h2 class="blog-text-center blog-title"><span>Contact ME</span></h2>
            <p>
                <a href=""><span class="am-icon-qq am-icon-fw am-primary blog-icon"></span></a>
                <a href=""><span class="am-icon-github am-icon-fw blog-icon"></span></a>
                <a href=""><span class="am-icon-weibo am-icon-fw blog-icon"></span></a>
                <a href=""><span class="am-icon-reddit am-icon-fw blog-icon"></span></a>
                <a href=""><span class="am-icon-weixin am-icon-fw blog-icon"></span></a>
            </p>
        </div>
        <div class="blog-clear-margin blog-sidebar-widget blog-bor am-g ">
            <h2 class="blog-title"><span>TAG cloud</span></h2>
            <div class="am-u-sm-12 blog-clear-padding">
            <a href="" class="blog-tag">amaze</a>
            <a href="" class="blog-tag">妹纸 UI</a>
            <a href="" class="blog-tag">HTML5</a>
            <a href="" class="blog-tag">这是标签</a>
            <a href="" class="blog-tag">Impossible</a>
            <a href="" class="blog-tag">开源框架</a>
            </div>
        </div>
        <div class="blog-sidebar-widget blog-bor">
            <h2 class="blog-title"><span>之言</span></h2>
            <ul class="am-list">
                <li><a href="#">每个人都有一个死角， 自己走不出来，别人也闯不进去。</a></li>
                <li><a href="#">我把最深沉的秘密放在那里。</a></li>
                <li><a href="#">你不懂我，我不怪你。</a></li>
                <li><a href="#">每个人都有一道伤口， 或深或浅，盖上布，以为不存在。</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- content end -->



  <footer class="blog-footer">
    <div class="am-g am-g-fixed blog-fixed am-u-sm-centered blog-footer-padding"></div>
  </footer>





<!--[if (gte IE 9)|!(IE)]><!-->
<script src="{% static 'self/assets/js/jquery.min.js' %}"></script>
<!--<![endif]-->
<!--[if lte IE 8 ]>
<script src="{% static 'self/assets/js/jquery.min.js' %}"></script>
<script src="{% static 'self/assets/js/modernizr.js' %}"></script>
<script src="{% static 'self/assets/js/amazeui.ie8polyfill.min.js' %}"></script>
<![endif]-->
<script src="{% static 'self/assets/js/amazeui.min.js' %}"></script>
</body>
</html>

self/templates/self/lianjie.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>个人主页</title>
  {% load static %}
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp"/>
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="Amaze UI"/>
  <link rel="stylesheet" href="{% static 'self/assets/css/amazeui.min.css' %}">
  <link rel="stylesheet" href="{% static 'self/assets/css/app.css' %}">
</head>

<body id="blog">

<!-- nav start -->
<nav class="am-g am-g-fixed blog-fixed blog-nav">
<button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only blog-button" data-am-collapse="{target: '#blog-collapse'}" ></button>

  <div class="am-collapse am-topbar-collapse" id="blog-collapse">
    <ul class="am-nav am-nav-pills am-topbar-nav">
      <li class="am-active"><a href="{% url 'self:index'%}">首页</a></li>
      <li><a href="{% url 'pingtai:index'%}">回到博客</a></li>
      <!--<li><a href="lw-article-fullwidth.html">更新</a></li>-->
      <li><a href="{% url 'self:liuyan'%}">留言</a></li>
      <li><a href="{% url 'self:lianjie'%}">链接</a></li>
      <li><a href="{% url 'self:loginout'%}">退出</a></li>
      <li><a href="{% url 'self:guanli'%}">管理</a></li>
    </ul>
    <form class="am-topbar-form am-topbar-right am-form-inline" role="search">
      <div class="am-form-group">
        <input type="text" class="am-form-field am-input-sm" placeholder="搜索">
      </div>
    </form>
  </div>
</nav>
<!-- content srart -->
<div class="am-g am-g-fixed blog-fixed blog-content">
    <div class="am-u-md-8 am-u-sm-12">
        <div class="am-g blog-author blog-article-margin">
          <hr>
          <h1 style="color: #0f9ae0">链接</h1>
          <h1>LIFE BLOG</h1>
          <div class="am-g blog-author blog-article-margin">
              <div class="am-u-sm-3 am-u-md-3 am-u-lg-2">
                <img src="{% static 'self/assets/i/f15.jpg' %}" alt="" class="blog-author-img am-circle">
              </div>
              <div class="am-u-sm-9 am-u-md-9 am-u-lg-10">
              <h3><a href=""><span class="blog-color">Amazeui</span></a></h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
              </div>
              <div class="am-u-sm-3 am-u-md-3 am-u-lg-2">
                <img src="{% static 'self/assets/i/f10.jpg' %}" alt="" class="blog-author-img am-circle">
              </div>
              <div class="am-u-sm-9 am-u-md-9 am-u-lg-10">
              <h3><a href=""><span class="blog-color">Meow</span></a></h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
              </div>
            <div class="am-u-sm-3 am-u-md-3 am-u-lg-2">
                <img src="{% static 'self/assets/i/f12.jpg' %}" alt="" class="blog-author-img am-circle">
              </div>
              <div class="am-u-sm-9 am-u-md-9 am-u-lg-10">
              <h3><a href=""><span class="blog-color">Timo</span></a></h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
              </div>
            <div class="am-u-sm-3 am-u-md-3 am-u-lg-2">
                <img src="{% static 'self/assets/i/f16.jpg' %}" alt="" class="blog-author-img am-circle">
              </div>
              <div class="am-u-sm-9 am-u-md-9 am-u-lg-10">
              <h3><a href=""><span class="blog-color">Yuanyuan</span></a></h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
              </div>
            </div>
          </div>
    </div>

    <div class="am-u-md-4 am-u-sm-12 blog-sidebar">
        <div class="blog-sidebar-widget blog-bor">
            <h2 class="blog-text-center blog-title"><span>About</span></h2>
            <img src="{% static 'self/assets/i/f14.jpg' %}" alt="about me" class="blog-entry-img" >
            <p>妹纸</p>
            <p>{{name}}</p>
        </div>
        <div class="blog-sidebar-widget blog-bor">
            <h2 class="blog-text-center blog-title"><span>Contact ME</span></h2>
            <p>
                <a href=""><span class="am-icon-qq am-icon-fw am-primary blog-icon"></span></a>
                <a href=""><span class="am-icon-github am-icon-fw blog-icon"></span></a>
                <a href=""><span class="am-icon-weibo am-icon-fw blog-icon"></span></a>
                <a href=""><span class="am-icon-reddit am-icon-fw blog-icon"></span></a>
                <a href=""><span class="am-icon-weixin am-icon-fw blog-icon"></span></a>
            </p>
        </div>
    </div>
</div>
<!-- content end -->

<!--[if (gte IE 9)|!(IE)]><!-->
<script src="{% static 'self/assets/js/jquery.min.js' %}"></script>
<!--<![endif]-->
<!--[if lte IE 8 ]>
<script src="{% static 'self/assets/js/jquery.min.js' %}"></script>
<script src="{% static 'self/assets/js/modernizr.js' %}"></script>
<script src="{% static 'self/assets/js/amazeui.ie8polyfill.min.js' %}"></script>
<![endif]-->
<script src="{% static 'self/assets/js/amazeui.min.js' %}"></script>
</body>
</html>

self/templates/self/selfadmin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>